### ISSUE TITLE
Liquid formatter throws error  

### ISSUE THREAD

**Issue by pie2211** [panoply/vscode-liquid#8]
Hey panoply, big fan of the extension, it was the main reason I moved away from my old editor to VSCode, so thanks for all your time and effort.

I'm experiencing a new issue since the update to 1.6.2 which fixes the ignore comments bug. The update  throws errors when formating using document and selection format commands:

`Liquid Document could not be formatted, check your code!` 

`Liquid Format Failed! The selection is invalid or incomplete!`

This has been tested on a bare bones liquid file containing a single liquid stastement, a clean install of VSCode (Win 64), a clean settings json and no other extensions installed.

Liquid files are auto detecting as HTML and I see no liquid switch in the bottom status bar for controlling Liquid formating on/off, in case any of that is relevant. 

Syntax highlighting, snippets and autocomplete are functioning as before.

**Comment by panoply** [comment]
Hey @pie2211 thanks for submitting this issue. I will look into what is causing this problems tonight. For the time being use version 1.6.1 or consider using formatting onSave.

**Comment by panoply** [comment]
@pie2211 This has been resolved in version 1.6.3.

**Comment by pie2211** [comment]
Great stuff Panopoly, received the extension update this morning.

For anyone who might stumble upon this post still having issues with liquid comments not being disabled by the extension:

Make sure you have no spaces between the brackets and tag name of the Liquid comments.

So `{%-comment-%}` or `{%comment%}` obeys the inbuilt ignore for comment tags

**but**

`{%- comment -%}` or `{% comment %}` still applies formatting to comments resulting in malformed code, even with ignore set on comments in settings JSON.

Just removes the spaces and you're good to go.
